### ISSUE TITLE
Clarify Installation Instructions

### ISSUE THREAD

**Issue by greggmarshall** [mikemadison13/blt-lando#10]
When I tried using `composer require mikemadison13/blt-lando`, I got the error response

>  [InvalidArgumentException]                                                                                                                                                            
>   Could not find a version of package mikemadison13/blt-lando matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.  

This is because the drupal/recommended-project sets a minimum stability of stable.

After a bit of Googling, I discovered that I could use `composer require mikemadison13/blt-lando:dev-main`.  Might want to add this option to the documentation or create a release for packagist.

**Comment by mikemadison13** [comment]
ah, we tend to use acquia/drupal-recommended-project instead of drupal/recommended-project so i haven't run into this. "stable" isn't a great level given how many modules aren't actually "stable" for d9 just yet. 

i'll see about updating the docs!
