### ISSUE TITLE
Instructions for "To start developing every time" say to set up an empty database

### ISSUE THREAD

**Issue by sara-ck** [mikemadison13/blt-lando#15]
Under "To start developing every time," it says:

> 5. Setup a local Drupal site with an empty database. The blt-cohesion composer package will run all necessary site studio commands. Use BLT to setup the site with configuration.
> $ lando blt setup

I wouldn't expect to have to create an empty database every time I start developing. Should this be `sync` instead of `setup`? Or am I misunderstanding what this step is saying?

**Comment by mikemadison13** [comment]
it depends on the task. sometimes you do want a clean / empty db / fresh drupal install, hence the `blt setup.` sometimes you do want existing content / users / etc synced down from a cloud environment, with `blt sync`. it could go either way depending on the situation!

**Comment by sara-ck** [comment]
Thanks for the quick response and explanation! I made a PR in case that information would be helpful for anyone else.
