### ISSUE TITLE
Issues in README

### ISSUE THREAD

**Issue by ba66e77** [mikemadison13/blt-lando#23]
Thanks for putting this repo together. Wish I'd found it before I _"figured out"_ the process for converting from DrupalVM to Lando. ;)

I noted a couple things in the README that may need a second look.

**Issue 1**
The --with-all-dependencies is not an option of `require` and throws an error if included.
```
composer require --dev mikemadison13/blt-lando --with-all-dependencies


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--with-all-dependencies" option does not exist.
```

**Issue 2**
> Initialize the Gitlab integration by calling...

Step 3 makes a reference to Gitlab but I don't see anywhere else referencing Gitlab integration. Is Gitlab here just a typo?

**Comment by mikemadison13** [comment]
issue 2 is definitely a typo. i'll fix that.

@bemarlan recently added the --with-all-dependencies flag because she said things were failing otherwise, i'll let the two of you sort that out!

**Comment by bemarlan** [comment]
@ba66e77 use `-W` if using composer 2, making it `composer require --dev mikemadison13/blt-lando -W`
cc @mikemadison13
