### ISSUE TITLE
Solr question

### ISSUE THREAD

**Issue by jedgar1mx** [mikemadison13/blt-lando#30]
Is there a way to test acquia search locally in lando?

Thanks

**Comment by mikemadison13** [comment]
@jedgar1mx i THINK that the newer version of Acquia Search allows for remote connections. So, sort of? You wouldn't actually have solr running locally, you would just have your local machine connect into your cloud Solr service.

the alternative is to setup a local solr service in Lando using something like https://github.com/mikemadison13/blt-lando#adding-solr which is technically just "search api + solr" and not true Acquia Search.

**Comment by jedgar1mx** [comment]
I will take a look at both options. Thanks @mikemadison13

**Comment by mikemadison13** [comment]
you betcha! good luck
